/*
 * This source file was generated by the Gradle 'init' task
 */
package ds_lab;
import java.util.*;

public class App {

    public static void main(String[] args) {
        System.out.println("Hello World!");

        Stack<Integer> stack = new Stack<>();
        stack.push(1);
        stack.push(2);
        stack.push(3);
        while (!stack.isEmpty()) {
            System.out.println(stack.pop());
        }
        stack.push(10);
        stack.push(20);
        stack.push(30);
        System.out.println(stack.peek());
        System.out.println(stack);

        stack.clear();
        System.out.println(stack);
        stack.push(100);
        stack.push(200);
        System.out.println(stack);
        stack.pop();

        Queue<Integer> queue = new LinkedList<>();
        queue.offer(1);
        queue.offer(2);
        queue.offer(3);
        while (!queue.isEmpty()) {
            System.out.println(queue.poll());
        }

        queue.clear();
        System.out.println(queue);
        queue.offer(100);
        queue.offer(200);
        System.out.println(queue);
        queue.poll();
        System.out.println(queue);
        queue.offer(300);
        queue.offer(400);
        System.out.println(queue);
        System.out.println(queue.peek());


        TreeSet<Integer> treeSet = new TreeSet<>();
        treeSet.add(5);
        treeSet.add(2);
        treeSet.add(8);
        treeSet.add(1);
        treeSet.add(3);

        System.out.println(treeSet);

        treeSet.remove(2);
        System.out.println(treeSet);

        System.out.println(treeSet.contains(3));


    }
}
